FROM python:3.12-slim

# Укажем рабочий каталог
WORKDIR /app
# Скопируем нужные (отфильтруем через .dockerignore лишнее) файлы проекта в /app контейнера
COPY . .
# Установим в контейнер зависимости для этого проекта (fastapi,uvicorn,mysql-connector-python)
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 